### PR TITLE
feat(react-components): export emoji popup component

### PR DESCRIPTION
**Pull request by ronnyroeller**
### Description

The EmojiPopupComponent renders the emoji suggestion dropdown for the user. The component existed so far only internal. This commit exposes it to public.

Discussed here: https://discord.com/channels/726035064831344711/745695521305526302/822569257090023424

### Checklist

- [x] I have read the [**contributing**](https://github.com/remirror/remirror/blob/HEAD/docs/contributing.md) document.
- [x] My code follows the code style of this project and `pnpm fix` completed successfully.
- [x] I have updated the documentation where necessary.
- [x] New code is unit tested and all current tests pass when running `pnpm test`.

### CODE REVIEW

**Review by ifiokjr — APPROVED** [review]
Lovely 😊

**Comment by ronnyroeller** [comment]
@ifiokjr General process question: After you approved a PR: is the idea that the contributor merges it into `beta` or are you doing this yourself at a later point?

**Comment by ifiokjr** [comment]
> General process question: After you approved a PR: is the idea that the contributor merges it into beta or are you doing this yourself at a later point?

@ronnyroeller I'm happy for you to merge after an approval.

I'll tidy up the PR a little since it's failing the build for some reason.

**Comment by ifiokjr** [comment]
This has been added in another pull request. Thanks for opening the PR 😄

**Pull request closed without merging**
