### PR TITLE
docs: fix typo in extension.md

### PR DESCRIPTION
**Pull request by Auk14HP**
Fix typo in extension.md

### Description
Small typo fix on the extension documentation page.

### Checklist

- [X] I have read the [**contributing**](https://github.com/remirror/remirror/blob/HEAD/docs/contributing.md) document.
- [X] My code follows the code style of this project and `pnpm fix` completed successfully.
- [X] I have updated the documentation where necessary.
- [X] New code is unit tested and all current tests pass when running `pnpm test`.

### Screenshots
n/a

### CODE REVIEW

**Comment by whawker** [comment]
Thanks for the contribution, but the language used here is correct.

**Comment by Auk14HP** [comment]
> Thanks for the contribution, but the language used here is correct.

It's not though. Using "and" after "via" is incorrect.

It'd be like saying "I went to work today via and electric car."

**Comment by whawker** [comment]
Apologies, I just realised I read the changeset back to front 🤦‍♂️

**Comment by whawker** [comment]
Thanks for the contribution, and apologies for the confusion

**Pull request merged**
