### PR TITLE
fix(extension-react-tables): use an earlier version of `jsx-dom`

### LINKED ISSUE #918: incompatible with Next.js
### Summary

`jsx-dom` only provides an ESM version. When using remirror with Next.js, Next.js prefers to use a CJS version of remirror(`remirror-extension-react-tables.cjs.prod.js`). This causes some kind of incompatibility.

### Steps to reproduce

Go to https://codesandbox.io/s/friendly-lovelace-jdeo7?file=/pages/index.js 
 
### Expected results

Not error.
 

### Actual results

```
pnpm build                                                                                                                                                                                                 

> nextjs@1.0.0 build /Users/ocavue/Downloads/jdeo7
> next build

info  - Using webpack 5. Reason: future.webpack5 option enabled https://nextjs.org/docs/messages/webpack5
info  - Checking validity of types
info  - Creating an optimized production build .<i> [webpack.cache.PackFileCacheStrategy/webpack.FileSystemInfo] Node.js doesn't offer a (nice) way to introspect the ESM dependency graph yet.
<i> Until a full solution is available webpack uses an experimental ESM tracking based on parsing.
<i> As best effort webpack parses the ESM files to guess dependencies. But this can lead to expensive and incorrect tracking.
info  - Creating an optimized production build ...<i> [webpack.cache.PackFileCacheStrategy/webpack.FileSystemInfo] Node.js doesn't offer a (nice) way to introspect the ESM dependency graph yet.
<i> Until a full solution is available webpack uses an experimental ESM tracking based on parsing.
<i> As best effort webpack parses the ESM files to guess dependencies. But this can lead to expensive and incorrect tracking.
info  - Creating an optimized production build
info  - Compiled successfully

> Build error occurred
/Users/ocavue/Downloads/jdeo7/node_modules/.pnpm/jsx-dom@7.0.0-beta.4/node_modules/jsx-dom/index.js:477
export default index
^^^^^^

SyntaxError: Unexpected token 'export'
    at Object.compileFunction (node:vm:355:18)
    at wrapSafe (node:internal/modules/cjs/loader:1022:15)
    at Module._compile (node:internal/modules/cjs/loader:1056:27)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1121:10)
    at Module.load (node:internal/modules/cjs/loader:972:32)
    at Function.Module._load (node:internal/modules/cjs/loader:813:14)
    at Module.require (node:internal/modules/cjs/loader:996:19)
    at require (node:internal/modules/cjs/helpers:92:18)
    at Object.<anonymous> (/Users/ocavue/Downloads/jdeo7/node_modules/.pnpm/@remirror/extension-react-tables@0.0.0-pr706.16_8547f15362ad3a3e586234df7980b79a/node_modules/@remirror/extension-react-tables/dist/remirror-extension-react-tables.cjs.prod.js:25:14)
    at Module._compile (node:internal/modules/cjs/loader:1092:14) {
  type: 'SyntaxError'
}
info  - Collecting page data . ERROR  Command failed with exit code 1.
```

### Possible Solution

Ask jsx-dom to provide both CJS and ESM builds. I can firstly fork jsx-dom to fix this issue.

See also https://github.com/proteriax/jsx-dom/pull/58

### PR DESCRIPTION
**Pull request by ocavue**
### Description

This PR replaces `jsx-dom` with a forked version. 

Fixes #918

### Checklist

- [x] I have read the [**contributing**](https://github.com/remirror/remirror/blob/HEAD/docs/contributing.md) document.
- [x] My code follows the code style of this project and `pnpm fix` completed successfully.
- [x] I have updated the documentation where necessary.
- [x] New code is unit tested and all current tests pass when running `pnpm test`.

### CODE REVIEW

**Comment by ifiokjr** [comment]
I'm nervous about using a github repo fork. 

What about using https://github.com/vadimdemedes/dom-chef or an earlier version of jsx-dom?

**Comment by ocavue** [comment]
@ifiokjr I will check your advices. 

Another option is copying the code from jsx-dom to the remirror. Since I don't actually use the "jsx" feature from this library, the amount of code that needed to be copied should be small.

**Comment by ocavue** [comment]
@ifiokjr Downgrade `jsx-dom` works🎉! I can't believe that I took so much time to re-implement a feature that has been deleted by the author. 😭

**Review by ifiokjr — APPROVED** [review]
Looks good

**Pull request merged**
