### PR TITLE
docs: add DocExtension documentation

### PR DESCRIPTION
**Pull request by stevebuik**
### Description

DocExtension docs page

### Checklist

- [x] I have read the [**contributing**](https://github.com/remirror/remirror/blob/HEAD/docs/contributing.md) document.
- [x] My code follows the code style of this project and `pnpm fix` completed successfully.
- [x] I have updated the documentation where necessary.
- [x] New code is unit tested and all current tests pass when running `pnpm test`.

### CODE REVIEW

**Comment by ocavue** [comment]
Thank you for your contribution! You can ignore the CI error about `lint-pr-name` by the way.

**Review by ocavue — APPROVED** [review]
LGTM

**Comment by ocavue** [comment]
@ronnyroeller Could you also check this PR. Thanks!

**Comment by ronnyroeller** [comment]
LGTM

**Pull request merged**
