### PR TITLE
export wysiwyg components

### PR DESCRIPTION
**Pull request by hboylan**
## Description

This change exports the components which comprise the `WysiwygEditor`, fixes the left margin of the bubble menu, and updates the corresponding imports in the advanced guide.

## Checklist

- [x] I have read the [**contributing**](https://github.com/ifiokjr/remirror/blob/master/docs/contributing.md) document.
- [x] My code follows the code style of this project and `yarn fix` runs successfully.
- [x] I have updated the documentation where necessary.
- [x] New code is unit tested and all current tests pass when running `yarn test` .

## Screenshots

Screen Shot 2020-02-04 at 7 04 14 PM
Screen Shot 2020-02-04 at 7 04 30 PM

### CODE REVIEW

**Comment by ifiokjr** [comment]
Hmmm, the commits seem to have become a bit jumbled up. Do you mind if I cherry pick your commit and push merge it separately?

**Comment by hboylan** [comment]
Sorry about that. Yes, please.

**Comment by ifiokjr** [comment]
I've added your commit in 9e66324a1973499ae8c7956663099e9ffa855737.

I'm happy to help with rebasing and merge conflicts if you ever need it. 

Thanks again 👍

**Comment by ifiokjr** [comment]
@all-contributors please add @hboylan for code.

**Comment by ifiokjr** [comment]
@all-contributors please add @hboylan for code

**Pull request closed without merging**
