### PR TITLE
Change "export * from" to fix TypeScript typing

### PR DESCRIPTION
**Pull request by giacomorebonato**
### Description

Some "export * from" don't work well with TypeScript with target "ESNext".
I am proposing to change them to a named export, if you think it's a good idea too.

### Checklist

- [x] I have read the [**contributing**](https://github.com/remirror/remirror/blob/HEAD/docs/contributing.md) document.
- [x] My code follows the code style of this project and `pnpm fix` completed successfully.
- [x] I have updated the documentation where necessary.
- [x] New code is unit tested and all current tests pass when running `pnpm test`.

### Screenshots

Screenshot 2023-03-04 at 14 25 24

### CODE REVIEW

**Comment by ocavue** [comment]
> Some "export * from" don't work well with TypeScript with target "ESNext".

What's the error message from TypeScript? A codesandbox reproduction will be better!

**Comment by giacomorebonato** [comment]
To reproduce the issue you can:

* clone [this repo](https://github.com/giacomorebonato/wysiwyg-markdown-react)
* install its dependencies `pnpm install`
* `cd packages/markdown-editor/`
* `npx tsc`

I couldn't find a way to reproduce it on Codesandbox

**Comment by ocavue** [comment]
Thanks. I can reproduce it. I will fix it.

**Comment by giacomorebonato** [comment]
Thank you!

**Pull request closed without merging**
