### PR TITLE
fix(remirror): export `remirror/styles`

### PR DESCRIPTION
**Pull request by ocavue**
### Description

Check details from #1123

### Checklist

- [x] I have read the [**contributing**](https://github.com/remirror/remirror/blob/HEAD/docs/contributing.md) document.
- [x] My code follows the code style of this project and `pnpm fix` completed successfully.
- [x] I have updated the documentation where necessary.
- [x] New code is unit tested and all current tests pass when running `pnpm test`.

### CODE REVIEW

**Comment by Tom910** [comment]
@ocavue Hi, thanks for fast mr and answer. I checked remirror@1.0.11 but exports don't have styles field - https://registry.npmjs.org/remirror/-/remirror-1.0.11.tgz -> package.json -> exports block

**Comment by ocavue** [comment]
I made a mistake. Will fix soon.

**Comment by ocavue** [comment]
@Tom910 I just released `remirror@1.0.12`. The `package.json` in this version does include `./styles`. Could you check if this version fixes your webpack issue?

**Comment by Tom910** [comment]
@ocavue Thanks, right now everything if fine

**Comment by ocavue** [comment]
@Tom910 awesome.

**Pull request merged**
