### PR TITLE
fix(link-extension): remove duplicate click handler

### PR DESCRIPTION
**Pull request by shlroland**
### Checklist

- [x] I have read the [**contributing**](https://github.com/remirror/remirror/blob/HEAD/docs/contributing.md) document.
- [x] My code follows the code style of this project and `pnpm fix` completed successfully.
- [x] I have updated the documentation where necessary.
- [x] New code is unit tested and all current tests pass when running `pnpm test`.

### CODE REVIEW

**Comment by ocavue** [comment]
Thanks. Could you also fix the failed test please?

**Comment by shlroland** [comment]
> Thanks. Could you also fix the failed test please?

These two failed test cases have left me confused. The click handler registered in createPlugin was being triggered, but the one registered in createEventHandlers was not being triggered. This phenomenon has resulted in the failure of the test cases.

**Comment by ocavue** [comment]
I think this is because the "click" handler register by `createEventHandlers` it actually a "mousedown" handler. 

So when you register the [`handleClick`](https://prosemirror.net/docs/ref/#view.EditorProps.handleClick) listener in ProseMirror, ProseMirror will register a [`mousedown`](https://github.com/prosemirror/prosemirror-view/blob/3534e1104774fd002288a0358bb22397ae8a6f50/src/input.ts#L288) handler. This handler will create a [`MouseDown`](https://github.com/prosemirror/prosemirror-view/blob/3534e1104774fd002288a0358bb22397ae8a6f50/src/input.ts#L304) object when `mousedown` event is fired, and that `MouseDown` object will later [fire your "click" event handler](https://github.com/prosemirror/prosemirror-view/blob/3534e1104774fd002288a0358bb22397ae8a6f50/src/input.ts#L395) when the `mouseup` event is fired.

**Comment by shlroland** [comment]
> When you register the [`handleClick`](https://prosemirror.net/docs/ref/#view.EditorProps.handleClick) listener in ProseMirror, ProseMirror will register a [`mousedown`](https://github.com/prosemirror/prosemirror-view/blob/3534e1104774fd002288a0358bb22397ae8a6f50/src/input.ts#L288) handler. This handler will create a [`MouseDown`](https://github.com/prosemirror/prosemirror-view/blob/3534e1104774fd002288a0358bb22397ae8a6f50/src/input.ts#L304) object when `mousedown` event is fired, and that `MouseDown` object will later [fire your "click" event handler](https://github.com/prosemirror/prosemirror-view/blob/3534e1104774fd002288a0358bb22397ae8a6f50/src/input.ts#L395) when the `mouseup` event is fired.
> 
> I guess the test will pass if you don't fire a click event, but a mousedown event and a mouseup event. I haven't test it myself so there might be some other details to notice.

I fixed it. EventsHandler use `clickOn` handler instead of `click`.I have written a new test case by mimicking the one for `onclick`.

**Comment by ocavue** [comment]
LGTM. Do you think we should revert https://github.com/remirror/remirror/pull/2072?

**Comment by shlroland** [comment]
> LGTM. Do you think we should revert #2072?

As mentioned in the comment, it is recommended to encourage the use of `onClick` to handle click events. Perhaps we can consider adding an `option` to give the control to the user, allowing them to decide whether the click event should be triggered when the component is disabled.

**Pull request merged**
