### PR TITLE
feat(editor-wysiwyg): show current link value in LinkInput

### PR DESCRIPTION
**Pull request by tomas-c**
## Description

Solves #111 

## Checklist

- [x] I have read the [**contributing**](https://github.com/remirror/remirror/blob/master/docs/contributing.md) document.
- [x] My code follows the code style of this project and `yarn fix` runs successfully.
- [x] I have updated the documentation where necessary.
- [x] New code is unit tested and all current tests pass when running `yarn test` .

### CODE REVIEW

**Comment by tomas-c** [comment]
Checks fail due to "Check for vulnerabilities" task, not related to the changes in this PR

**Comment by tomas-c** [comment]
Another alternative implementation could be to pass the current link attributes to the LinkExtension's activationHandler [here](https://github.com/remirror/remirror/blob/29c8ef4651ece848be7a70d944415c6c14c7c840/%40remirror/core-extensions/src/marks/link-extension.ts#L88)

**Comment by ifiokjr** [comment]
> Checks fail due to "Check for vulnerabilities" task, not related to the changes in this PR

I've just updated the `yarn.lock` file so merging should be possible now. Everything looks good at a glance. I'll just take a look when I have a few more minutes before merging.

**Comment by ifiokjr** [comment]
> Another alternative implementation could be to pass the current link attributes to the LinkExtension's activationHandler here

I like this idea in addition to what you've done.

**Comment by ifiokjr** [comment]
Okay, I've rebased on top of the latest `canary`. If it passes I'll merge 😄

**Comment by tomas-c** [comment]
> > Another alternative implementation could be to pass the current link attributes to the LinkExtension's activationHandler here
> 
> I like this idea in addition to what you've done.

@ifiokjr I've had a second look and realized that [LinkExtension](https://github.com/remirror/remirror/blob/29c8ef4651ece848be7a70d944415c6c14c7c840/%40remirror/core-extensions/src/marks/link-extension.ts#L88) is not the only one that calls the handler, it's also called by [MenuBar](https://github.com/remirror/remirror/blob/db20a731608970a4948fc97faf8c3a31bd6df333/%40remirror/editor-wysiwyg/src/components/wysiwyg-menu.tsx#L107) so putting active link attribute detection inside the first location is not enough. 

Options I could think of:

1. Leave this as it is now
2. Add current link attributes as PluginState which will require doing something like `const defaultLinkValue = manager.getPluginState<LinkExtensionState>('link')?.currentLinkAttrs?.href as string | undefined;` to get the current href
3. Add some sort of helper method / state selector that is exported from link-extension.ts that wraps `getMarkAttrs(state.newState, manager.schema.marks.link).href`

Option 2 unnecessarily adds a state variable and function call on every transaction. Option 3 in effect only changes the name of the function that has to be called from `getMarkAttrs` to something custom - not much benefit. 

I think it makes sense to leave this as it is unless there's a better way.

**Pull request merged**
