### PR TITLE
chore(deps): update yjs packages

### PR DESCRIPTION
**Pull request by ocavue**
### Description

Update YJS packages to latest version, which is needed for #1448

### Checklist

- [ ] I have read the [**contributing**](https://github.com/remirror/remirror/blob/HEAD/docs/contributing.md) document.
- [ ] My code follows the code style of this project and `pnpm fix` completed successfully.
- [ ] I have updated the documentation where necessary.
- [ ] New code is unit tested and all current tests pass when running `pnpm test`.

### CODE REVIEW

**Comment by ocavue** [comment]
Jest tests can't pass because of the following error:

```
FAIL packages/remirror__extension-list/__tests__/list-extensions.spec.ts
  ● Test suite failed to run

    Jest encountered an unexpected token

    Jest failed to parse a file. This happens e.g. when your code or its dependencies use non-standard JavaScript syntax, or when Jest is not configured to support such syntax.

    Out of the box Jest supports Babel, which will be used to transform your files into valid JS based on your Babel configuration.

    By default "node_modules" folder is ignored by transformers.

    Here's what you can do:
     • If you are trying to use ECMAScript Modules, see https://jestjs.io/docs/ecmascript-modules for how to enable it.
     • If you are trying to use TypeScript, see https://jestjs.io/docs/getting-started#using-typescript
     • To have some of your "node_modules" files transformed, you can specify a custom "transformIgnorePatterns" in your config.
     • If you need a custom transformation specify a "transform" option in your config.
     • If you simply want to mock your non-JS modules (e.g. binary assets) you can stub them out with the "moduleNameMapper" config option.

    You'll find more details and examples of these config options in the docs:
    https://jestjs.io/docs/configuration
    For information about custom transformations, see:
    https://jestjs.io/docs/code-transformation

    Details:

    /home/runner/work/remirror/remirror/node_modules/.pnpm/y-protocols@1.0.5/node_modules/y-protocols/awareness.js:5
    import * as encoding from 'lib0/encoding'
    ^^^^^^

    SyntaxError: Cannot use import statement outside a module

      at Runtime.createScriptFromCode (node_modules/.pnpm/jest-runtime@27.3.1/node_modules/jest-runtime/build/index.js:1728:14)
      at Object.<anonymous> (node_modules/.pnpm/y-prosemirror@1.0.14_y-protocols@1.0.5+yjs@13.5.23/node_modules/y-prosemirror/dist/y-prosemirror.cjs:8:1)
```

**Comment by ankon** [comment]
I have flashbacks.

I think I solved this in our forked extension through a `transformIgnorePattern`: https://github.com/Collaborne/remirror-extension-yjs/blob/f05482fd7e845d1553850ef6bbaba465e772fdc2/package.json#L91-L93. But, we don't use pnpm, and it seems pnpm adds complexity here: https://github.com/facebook/jest/issues/2081#issuecomment-699558143

I'm trying to figure out whether that can be adapted, but so far no luck (and very likely I'm looking at the wrong jest configuration file -- right now guessing it's `jest/jest.config.js`)

**Comment by ankon** [comment]
Use this patch to ensure that lib0 and y-protocols are transformed:

```diff
diff --git a/support/jest/jest.config.js b/support/jest/jest.config.js
index d4fd678b0..8cbfc015f 100644
--- a/support/jest/jest.config.js
+++ b/support/jest/jest.config.js
@@ -15,6 +15,7 @@ module.exports = {
   transform: {
     '^.+\\.(js|jsx|ts|tsx|mjs)$': [require.resolve('babel-jest'), { rootMode: 'upward' }],
   },
+  transformIgnorePatterns: ['node_modules(?!/(.+/)*(lib0|y-protocols)[@/])'],
   moduleDirectories: ['node_modules'],
   testPathIgnorePatterns: ['<rootDir>/lib/', '<rootDir>/node_modules/'],
   testRegex: '/__tests__/.*\\.spec\\.tsx?$',
```

(Had to poke into babel-jest to log out which paths it is working on, and then adapted the RE to include the two packages that are needed)

**Comment by ocavue** [comment]
Wow, you are awesome! The workaround in Jest works great. I will close this PR and approve #1457 instead. 

I was thinking of submitting a PR to `y-protocols` and making it a CJS+ESM package. Currently, `y-protocols` is a pure ESM package, and `y-prosemirror` is a mixed CJS+ESM package. A mixed CJS+ESM package (or a pure CJS package) should not depend on a pure ESM package, because there is no direct way to import an ESM package in a CJS package without using async dynamic `import()`.

**Pull request closed without merging**
