### PR TITLE
feat(theme): remove default selection colors

### PR DESCRIPTION
**Pull request by ocavue**
### Description

This PR removes the following CSS variables and related config from `@remirror/theme` and `@remirror/style`. 

```
  --rmr-color-selection-background: Highlight;
  --rmr-color-selection-shadow: inherit;
  --rmr-color-selection-text: HighlightText;
  --rmr-color-selection-caret: inherit;
```

This brings two improvements for selection.

Firstly, the selection will get gray when the window loses the focus: 

https://user-images.githubusercontent.com/24715727/176670648-7e1e6e27-d8f8-4f6c-96e5-70999704cd06.mp4

Secondly, a selected link won't have black text color: 

image

### Checklist

- [ ] I have read the [**contributing**](https://github.com/remirror/remirror/blob/HEAD/docs/contributing.md) document.
- [ ] My code follows the code style of this project and `pnpm fix` completed successfully.
- [ ] I have updated the documentation where necessary.
- [ ] New code is unit tested and all current tests pass when running `pnpm test`.

### CODE REVIEW

**Comment by ocavue** [comment]
@whawker @ronnyroeller This would be a (small) breaking changes. What do you think?

**Review by ronnyroeller — APPROVED** [review]
v2 would be the right time to do this. Could you pls add to the release announcement/upgrade guide?

**Comment by whawker** [comment]
Any reason for removing, rather than just making them `inherit`?

**Comment by ocavue** [comment]
> Any reason for removing, rather than just making them `inherit`?



I tried to set all these four variables to `inherit`, but the selection background just disappear (see the video below). I couldn't find much information about the `Highlight` and `HighlightText` in CSS, so I'm not sure why.

https://user-images.githubusercontent.com/24715727/176681581-c97d8183-517d-4ec1-ad1b-e755cf128a91.mp4



I guess maybe it's much simpler to just not override selection CSS. If users do want to have some fancy selection, it's very easy for them to write some Vanilla CSS, instead of finding CSS variable names from Remirror's docs and trying to override these variables with correct CSS priority.

**Pull request merged**
