### PR TITLE
fix: w3c-keyname removed default import

### PR DESCRIPTION
**Pull request by Enalmada**
## Description

`wysiwig` doesn't work for me without this change.  

Seems like default import was removed in v2 so this change is required if w3c-keyname v2.x is to be used.
https://github.com/marijnh/w3c-keyname/releases/tag/2.0.0

```
ModuleDependencyError: "export 'default' (imported as 'keyNames') was not found in 'w3c-keyname'
```

I also pushed an update to package.json fixing prettier for windows.

## Checklist

- [x] I have read the [**contributing**](https://github.com/remirror/remirror/blob/master/docs/contributing.md) document.
- [x] I have updated the documentation where necessary.

- [x] My code follows the code style of this project and `yarn fix` runs successfully.  

- [ ] New code is unit tested and all current tests pass when running `yarn test`
> not all tests pass (see comment below) but it seems like the wysiwig ones do.

### CODE REVIEW

**Comment by ifiokjr** [comment]
Can you paste the error you were seeing?

**Comment by ifiokjr** [comment]
Also I'd be curious to know about `yarn fix` and `yarn test` failures on windows. What errors are you seeing?

**Comment by Enalmada** [comment]
if I run `yarn fix`
```
remirror>yarn fix
yarn run v1.22.4
$ run-s fix:prettier fix:es
$ yarn run:prettier --write
$ prettier --ignore-path .eslintignore '**/*.{js,jsx,ts,tsx,md,json,html,css,yml,yaml,graphql}' --write
[error] No matching files. Patterns tried: '**/*.{js,jsx,ts,tsx,md,json,html,css,yml,yaml,graphql}' !**/node_modules/** !./node_modules/** !**/.{git,svn,hg}/** !./.{git,svn,hg}/**
error Command failed with exit code 2.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
error Command failed with exit code 2.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
ERROR: "fix:prettier" exited with 2.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
``` 

if I run `yarn test` I get this for summary
```
=============================== Coverage summary ===============================
Statements   : 70.5% ( 3604/5112 )
Branches     : 56% ( 1499/2677 )
Functions    : 65.33% ( 1072/1641 )
Lines        : 71.07% ( 3479/4895 )
================================================================================
Summary of all failing tests
 FAIL  support/dts-jest/jest-prosemirror.dts.ts
  ● Test suite failed to run

    Jest encountered an unexpected token

    This usually means that you are trying to import a file which Jest cannot parse, e.g. it's not plain JavaScript.

    By default, if Jest sees a Babel config, it will use that to transform your files, ignoring "node_modules".

    Here's what you can do:
     • To have some of your "node_modules" files transformed, you can specify a custom "transformIgnorePatterns" in your config.
     • If you need a custom transformation specify a "transform" option in your config.
     • If you simply want to mock your non-JS modules (e.g. binary assets) you can stub them out with the "moduleNameMapper" config option.

    You'll find more details and examples of these config options in the docs:
    https://jestjs.io/docs/en/configuration.html

    Details:

    C:\Users\enalm\code\nodabl\research\remirror\support\dts-jest\jest-prosemirror.dts.ts:1
    import { EventType as DomEventType } from '@testing-library/dom';
    ^^^^^^

    SyntaxError: Cannot use import statement outside a module

      at Runtime._execModule (../../node_modules/jest-runtime/build/index.js:988:58)

 FAIL  support/dts-jest/extension-manager.dts.ts
  ● Test suite failed to run

    Jest encountered an unexpected token

    This usually means that you are trying to import a file which Jest cannot parse, e.g. it's not plain JavaScript.

    By default, if Jest sees a Babel config, it will use that to transform your files, ignoring "node_modules".

    Here's what you can do:
     • To have some of your "node_modules" files transformed, you can specify a custom "transformIgnorePatterns" in your config.
     • If you need a custom transformation specify a "transform" option in your config.
     • If you simply want to mock your non-JS modules (e.g. binary assets) you can stub them out with the "moduleNameMapper" config option.

    You'll find more details and examples of these config options in the docs:
    https://jestjs.io/docs/en/configuration.html

    Details:

    C:\Users\enalm\code\nodabl\research\remirror\support\dts-jest\extension-manager.dts.ts:1
    import {
    ^^^^^^

    SyntaxError: Cannot use import statement outside a module

      at Runtime._execModule (../../node_modules/jest-runtime/build/index.js:988:58)

 FAIL  support/dts-jest/extension-drop-cursor.dts.ts
  ● Test suite failed to run

    Jest encountered an unexpected token

    This usually means that you are trying to import a file which Jest cannot parse, e.g. it's not plain JavaScript.

    By default, if Jest sees a Babel config, it will use that to transform your files, ignoring "node_modules".

    Here's what you can do:
     • To have some of your "node_modules" files transformed, you can specify a custom "transformIgnorePatterns" in your config.
     • If you need a custom transformation specify a "transform" option in your config.
     • If you simply want to mock your non-JS modules (e.g. binary assets) you can stub them out with the "moduleNameMapper" config option.

    You'll find more details and examples of these config options in the docs:
    https://jestjs.io/docs/en/configuration.html

    Details:

    C:\Users\enalm\code\nodabl\research\remirror\support\dts-jest\extension-drop-cursor.dts.ts:1
    import { HelpersFromExtensions } from '@remirror/core';
    ^^^^^^

    SyntaxError: Cannot use import statement outside a module

      at Runtime._execModule (../../node_modules/jest-runtime/build/index.js:988:58)


Test Suites: 3 failed, 1 skipped, 71 passed, 74 of 75 total
Tests:       2 skipped, 606 passed, 608 total
Snapshots:   47 passed, 47 total
Time:        25.457s, estimated 31s
Ran all test suites in 29 projects.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

**Comment by Enalmada** [comment]
I did make sure the "Allow edits from maintainers." was checked when I created the PR.
image

**Comment by Enalmada** [comment]
I pushed a change to package.json allowing prettier to work on windows.  I believe this change is cross platform.

**Comment by ifiokjr** [comment]
@all-contributors please add @Enalmada for code and bug fixes.

**Pull request merged**
