### PR TITLE
Realtime editing demo

### PR DESCRIPTION
**Pull request by benjie**
## Description

Adds an example of how to use realtime prosemirror editing using [yjs](https://github.com/yjs/yjs)'s [prosemirror support](https://github.com/yjs/y-prosemirror) and the [websocket transport](https://github.com/yjs/y-websocket).

I'd like some guidance on how best to achieve this to Remirror. It works, but it's pretty flaky.

## Checklist

- [x] I have read the [**contributing**](https://github.com/remirror/remirror/blob/master/docs/contributing.md) document.
- [x] My code follows the code style of this project and `yarn fix` runs successfully.
- [x] I have updated the documentation where necessary.
- [x] New code is unit tested and all current tests pass when running `yarn test` .

## Screenshots
Peek 2020-02-20 15-54

### CODE REVIEW

**Comment by dmonad** [comment]
Really cool work @benjie ! 

It might make sense to use [y-webrtc](https://github.com/yjs/y-webrtc) so the remirror project doesn't have to run a y-websocket server for the remirror website. https://yjs.dev also runs on y-webrtc.

I'd be happy to receive a PR that includes this demo in https://github.com/yjs/yjs-demos too!

What was the "flaky" behavior you were experiencing?

**Comment by benjie** [comment]
Thanks @dmonad! The flakiness was from Remirror rather than yjs; and don't worry - we're working on it :) (Well, Ifi's working on it whilst I shout encouragement from the side-lines...)

I'm planning to rebuild this on the new Remirror soon, so your feedback is very timely! :raised_hands:

**Comment by dmonad** [comment]
Nice! Looking forward to this 🤩

**Comment by benjie** [comment]
This PR has been replaced by https://github.com/remirror/remirror/pull/319 - thanks for your guidance @dmonad!

**Pull request closed without merging**
