### PR TITLE
Bidi support

### PR DESCRIPTION
**Pull request by ifiokjr**
## Description

This adds bidirectional support to the editor.

## Checklist

- [x] I have read the [**contributing**](https://github.com/remirror/remirror/blob/master/docs/contributing.md) document.
- [x] My code follows the code style of this project and `yarn fix` runs successfully.
- [x] I have updated the documentation where necessary.
- [x] New code is unit tested and all current tests pass when running `yarn test` .

## Screenshots

It's not perfect but it's a good starting point. I'll need those who are more familiar with best practises for bidirectional text to help out where possible.

### CODE REVIEW

**Comment by ifiokjr** [comment]
It'd be great if someone who regularly types left to right could take a look at this.

**Comment by sijad** [comment]
can you please let me how can I test this? I've cloned this and run `yarn docs` in `bidi-support` branch but bidi does not works.
also I've got two error which I'm not sure if they are related to this changes:

1. if firefox (nighty version) spacebar key does not work
2. in chrome when I try to type `@abc  ` (mentions + double space) I got this error:

[
2020-06-18-14:03:56-screenshot
](url)

**Comment by ifiokjr** [comment]
Thanks for looking @sijad  

Sadly the mentions plugin is currently broken. I recently added controlled editor functionality and since the integration tests are not yet switched back on some broken functionality wasn't flagged in the unit tests. 

I'll create a fix for the mentions once the `extension-bidi` is working properly.  

Also the bidirectional support currently only works with initial content. I'm adding the dynamic part at the moment.

**Comment by ifiokjr** [comment]
@sijad I've added the dynamic element to the editor. I'll merge this into `next` for now. It's far from perfect, but I've added a some new API's to this branch that I will also need elsewhere. 

How open are you to helping out?

- Right now you can set the default direction, and turn off automatic updates. 

Could you try typing in the editor in multiple languages, how does it feel to you? What would you like to change?

**Note:** You can ignore the broken mentions' plugin. I'm looking into it now as part of an integration test update.

**Comment by sijad** [comment]
I've tested it with disabled auto update and it's perfect
Thank you so much

I might be able to help you with `autoUpdate` if you want

**Comment by ifiokjr** [comment]
Your help would be much appreciated. I'm available to answer any questions you may have.

**Pull request merged**
