### PR TITLE
feat: use stage-3 ES decorator

### PR DESCRIPTION
**Pull request by ocavue**
### Checklist

- [ ] I have read the [**contributing**](https://github.com/remirror/remirror/blob/HEAD/docs/contributing.md) document.
- [ ] My code follows the code style of this project and `pnpm fix` completed successfully.
- [ ] I have updated the documentation where necessary.
- [ ] New code is unit tested and all current tests pass when running `pnpm test`.

### CODE REVIEW

**Comment by ocavue** [comment]
Emmmm ESBuild doesn't support transform stage-3 decorator yet. We might need to wait it to support it. 



> https://github.com/evanw/esbuild/releases/tag/v0.18.5
> 
> Transforming JavaScript decorators to environments that don't support them has not been implemented yet. The only decorator transform that esbuild currently implements is still the TypeScript experimental decorator transform

**Comment by whawker** [comment]
Happy to postpone this one for the time being then?

**Comment by ocavue** [comment]
I guess we can wait for ESBuild to support this at this moment. If it takes too long, I could write a simple ESBuild plugin to transform stage-3 decorator myself, since we only need a small part of the stage-3 decorator syntax.

**Comment by whawker** [comment]
Given those options I would rather go for the custom plugin option if that's ok? I would rather not wait personally, I'm keen to get the Lingui #2128 stuff out (as a beta first)

**Comment by ocavue** [comment]
OK I'll try to create a custom plugin.

**Comment by ocavue** [comment]
Currently blocked by https://github.com/evanw/esbuild/issues/3396

**Comment by ocavue** [comment]
Closing this PR and moving to a new PR https://github.com/remirror/remirror/pull/2166, because of some weird issues about the NPM tag `pr2156`.

**Pull request closed without merging**
