### PR TITLE
docs: explain how to embed SocialEditor in CRA

### PR DESCRIPTION
**Pull request by ronnyroeller**
### Description

Add quick start tutorial

### Checklist

- [x] I have read the [**contributing**](https://github.com/remirror/remirror/blob/HEAD/docs/contributing.md) document.
- [x] My code follows the code style of this project and `pnpm fix` completed successfully.
- [x] I have updated the documentation where necessary.
- [x] New code is unit tested and all current tests pass when running `pnpm test`.

### CODE REVIEW

**Comment by ocavue** [comment]
CleanShot 2021-10-01 at 17 08 58

The argument in the function `t` will be emitted after building, which causes the error we saw in CRA. I'll try to update dependencies and see if that can fix this issue.

**Comment by ocavue** [comment]
We didn't release new versions of `@remirror/i18n` and `@remirror/message` for https://github.com/remirror/remirror/pull/1157, and that's why CRA example can't work. I will fix that.

**Comment by ocavue** [comment]
This is fixed in #1277

**Comment by ronnyroeller** [comment]
Thanks a lot, @ocavue . Works like a charm!

**Pull request merged**
