### PR TITLE
Add link to current remirror homepage

### PR DESCRIPTION
**Pull request by ankon**
Fixes https://github.com/remirror/remirror/issues/613

### Description

Added a note on the homepage and the first page that opens when you click "Documentation" to inform people that they should only be here if they want to be here.

### Checklist

- [x] I have read the [**contributing**](https://github.com/remirror/remirror/blob/HEAD/docs/contributing.md) document.
- [ ] ~My code follows the code style of this project and `pnpm fix` completed successfully.~ (docs on old branch: `pnpm fix` wants to do a lot of changes that are unrelated and blow up the diff)
- [x] I have updated the documentation where necessary.
- [ ] ~New code is unit tested and all current tests pass when running `pnpm test`.~

### CODE REVIEW

**Review by ifiokjr — APPROVED** [review]
Thanks for this. I've realised that 0.x isn't properly set up to auto-deploy, so I'll have to take a look at forcing a deployment later today.

**Comment by ankon** [comment]
Thanks a lot!

**Comment by ifiokjr** [comment]
It actually is set up for auto deployments, I just wasn't being patient, enough. I'll wait for the deploy preview before merging. 

Btw, did you try `yarn fix`?

**Comment by ankon** [comment]
> Btw, did you try `yarn fix`?

I ran `pnpm fix`, which started to reorganize each package.json file to move the `files` section around. I intentionally skipped these changes in the PR, as it made finding the actual change hard and these had nothing to do with my changes. If you want me to include these I can do that, sure.

(FWIW: I also had to temporarily remove the content from the social and wysiwyg showcase mdx, because gatsby was unhappy about not being able to find the @remirror/showcase package reference.)

**Comment by ankon** [comment]
... I see. CI wants these to be nice. Very well then, I'll add them :)

**Comment by ifiokjr** [comment]
Don't worry about fixing, it. There's a lot more issues with the build than just linting. I think a lot of dependencies are broken, due to months without update, so will need to go back and update the build and dependencies. Probably towards the end of this week.

**Comment by ifiokjr** [comment]
I've created a new issue to track this. Right now I don't have time to start on it. If you're able to dive in, I'm happy to support and will respond pretty quickly #615.

**Pull request merged**
