### PR TITLE
Update incorrect `Hello Remirror` docs

### PR DESCRIPTION
**Pull request by Bertg**
- Remove TS specific code
- Ensure labels are returned for mention logic
- Ensure all React methods are imported
- Rename  ```onChange``` to ```onMentionChange```
- Remove ```console.log```
- Rename "junk" to "example"

### Checklist

- [ ] I have read the [**contributing**](https://github.com/remirror/remirror/blob/HEAD/docs/contributing.md) document.
- [ ] My code follows the code style of this project and `pnpm fix` completed successfully.
- [ ] I have updated the documentation where necessary.
- [ ] New code is unit tested and all current tests pass when running `pnpm test`.

### CODE REVIEW

**Review by ifiokjr — APPROVED** [review]
Thanks for this 👍

**Comment by ifiokjr** [comment]
@Bertg looks like the linting is failing. `pnpm fix` should resolve it.

**Comment by ifiokjr** [comment]
For some reason I can't checkout your PR to make the changes myself.

**Comment by Bertg** [comment]
@ifiokjr All green!

**Pull request merged**
